# --- BUILD STAGE ---
FROM node:20 AS builder

WORKDIR /app

COPY package*.json ./
RUN yarn install

COPY . .
RUN yarn build

# --- PRODUCTION STAGE ---
FROM nginx:alpine

# Копіюємо готовий білд з builder-стадії в Nginx html-папку
COPY --from=builder /app/dist /usr/share/nginx/html

# (Опціонально) Якщо маєш свій nginx.conf, можеш підкинути сюди:
# COPY nginx.conf /etc/nginx/nginx.conf

EXPOSE 80

CMD ["nginx", "-g", "daemon off;"]